100719 lab
lumapps/samples pull request #4
Opened 2019-07-11 08:34 UTC by maximevast

Update readme, add images, improve examples

2019-07-18 14:41 UTC, maximevast commented
@josuemoens

2019-07-24 22:44 UTC, josuemoens requested changes
Seems good to me. Could you just translate the examples in English (January, February...) and use more international cities (Paris, New York...)

2019-07-25 12:24 UTC, maximevast commented
Hum... I forgot to update the readme, I will have to update the screen captures as well

2019-07-31 02:27 UTC, josuemoens approved these changes

2019-07-31 06:06 UTC, merged